### ISSUE TITLE
InternalOAuthError: Failed to obtain access token

### ISSUE THREAD

**Issue by LunaSquee** [julianlam/nodebb-plugin-sso-oauth#19]
I updated NodeBB to 1.5.3 and now I'm getting this every time I try to log in using OAuth:
```
 InternalOAuthError: Failed to obtain access token
    at OAuth2Strategy._createOAuthError (/var/www/service/nodebb/node_modules/passport-oauth2/lib/strategy.js:379:17)
    at /var/www/service/nodebb/node_modules/passport-oauth2/lib/strategy.js:166:45
    at /var/www/service/nodebb/node_modules/oauth/lib/oauth2.js:191:18
    at ClientRequest.<anonymous> (/var/www/service/nodebb/node_modules/oauth/lib/oauth2.js:162:5)
    at ClientRequest.emit (events.js:159:13)
    at TLSSocket.socketErrorListener (_http_client.js:389:9)
    at TLSSocket.emit (events.js:159:13)
    at onwriteError (_stream_writable.js:409:12)
    at onwrite (_stream_writable.js:431:5)
    at _destroy (internal/streams/destroy.js:39:7)
    at TLSSocket.Socket._destroy (net.js:565:3)
    at TLSSocket.destroy (internal/streams/destroy.js:32:8)
    at WriteWrap.afterWrite [as oncomplete] (net.js:875:10)
```
Looking at my OAuth2 provider's logs, it doesn't even seem to fire a POST to the token endpoint. Any ideas?

**Comment by LunaSquee** [comment]
After doing some deeper digging, I found out that it's an issue with the latest node.js regarding TLS ecdh_curve not being set to "auto" by default, so a request to my HTTPS site didn't work.
